#!/bin/bash
# plays youtube link from clipboard in mplayer
# uses youtube-dl to fetch video file
# Searches for 640x360 size video, or, in its absent, show list of codes,resolution pairs which this command can be retried  with
ytlink=`xclip -o`
ytlink=${ytlink%%&*}
if [ "$#" -gt 0 ]; then
	chosenFormat="-f $1"
else
	youtubeDlTmpFile=/tmp/youtube-dl-F-responce
	echo getting video mode for $ytlink
	youtube-dl -F $ytlink >$youtubeDlTmpFile
	chosenFormat="-f `tail -n +5 $youtubeDlTmpFile|grep 640x360 |tail -n 1|sed 's/ .*//'`"
fi
execMP="--exec mplayer"

downloaddir=/mnt/hede/home/multimedia/video/play
if [ -d "$downloaddir" ]; then
    cd $downloaddir
fi

#echo chosen format: $chosenFormat has length ${#chosenFormat}
if [ "${#chosenFormat}" -lt 4 ]; then
	cat  $youtubeDlTmpFile
else
	youtube-dl --restrict-filenames  $execMP $chosenFormat $ytlink
fi
