#!/bin/bash
# listen to podcast using url guessing, given a date in yyyy-mm-dd format as argument 
# hjernekassen
# https://www.dr.dk/mu/MediaRedirector/WithFileExtension/hjernekassen-pa-p1-2019-11-04.mp3?highestBitrate=True&podcastDownload=True
#
commontail=".mp3?highestBitrate=True&podcastDownload=True"
commonhead="https://www.dr.dk/mu/MediaRedirector/WithFileExtension/"
progOrientering="orientering-"
if date -d $1 >/dev/null 2>&1 && [ "${#1}" = "10" ]  ;  then
	audacious "${commonhead}${progOrientering}${1}${commontail}" &
else
	echo "$1 ? - use yyyy-mm-dd"
fi